package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGameRecharge;
import org.linlinjava.litemall.db.domain.LitemallGameRechargeExample;

public interface LitemallGameRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    long countByExample(LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int insert(LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameRecharge selectOneByExample(LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameRecharge selectOneByExampleSelective(@Param("example") LitemallGameRechargeExample example, @Param("selective") LitemallGameRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallGameRecharge> selectByExampleSelective(@Param("example") LitemallGameRechargeExample example, @Param("selective") LitemallGameRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    List<LitemallGameRecharge> selectByExample(LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameRecharge selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGameRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    LitemallGameRecharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameRecharge selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallGameRecharge record, @Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallGameRecharge record, @Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGameRecharge record, @Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGameRecharge record, @Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGameRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallGameRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}