package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGameGift;
import org.linlinjava.litemall.db.domain.LitemallGameGiftExample;

public interface LitemallGameGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    long countByExample(LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int insert(LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameGift selectOneByExample(LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameGift selectOneByExampleSelective(@Param("example") LitemallGameGiftExample example, @Param("selective") LitemallGameGift.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallGameGift> selectByExampleSelective(@Param("example") LitemallGameGiftExample example, @Param("selective") LitemallGameGift.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    List<LitemallGameGift> selectByExample(LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameGift selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGameGift.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    LitemallGameGift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameGift selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallGameGift record, @Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallGameGift record, @Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGameGift record, @Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGameGift record, @Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGameGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallGameGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_gift
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}