package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallExperienceLog;
import org.linlinjava.litemall.db.domain.LitemallExperienceLogExample;

public interface LitemallExperienceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int insert(LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExperienceLog selectOneByExample(LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExperienceLog selectOneByExampleSelective(@Param("example") LitemallExperienceLogExample example, @Param("selective") LitemallExperienceLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallExperienceLog> selectByExampleSelective(@Param("example") LitemallExperienceLogExample example, @Param("selective") LitemallExperienceLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    List<LitemallExperienceLog> selectByExample(LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExperienceLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallExperienceLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    LitemallExperienceLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExperienceLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallExperienceLog record, @Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallExperienceLog record, @Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallExperienceLog record, @Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallExperienceLog record, @Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallExperienceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallExperienceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_experience_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}