package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMemberLevel;
import org.linlinjava.litemall.db.domain.LitemallMemberLevelExample;

public interface LitemallMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    long countByExample(LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int insert(LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberLevel selectOneByExample(LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberLevel selectOneByExampleSelective(@Param("example") LitemallMemberLevelExample example, @Param("selective") LitemallMemberLevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallMemberLevel> selectByExampleSelective(@Param("example") LitemallMemberLevelExample example, @Param("selective") LitemallMemberLevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    List<LitemallMemberLevel> selectByExample(LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberLevel selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMemberLevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    LitemallMemberLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberLevel selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallMemberLevel record, @Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallMemberLevel record, @Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMemberLevel record, @Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMemberLevel record, @Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_level
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}