package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGameLog;
import org.linlinjava.litemall.db.domain.LitemallGameLogExample;

public interface LitemallGameLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int insert(LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameLog selectOneByExample(LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameLog selectOneByExampleSelective(@Param("example") LitemallGameLogExample example, @Param("selective") LitemallGameLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallGameLog> selectByExampleSelective(@Param("example") LitemallGameLogExample example, @Param("selective") LitemallGameLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    List<LitemallGameLog> selectByExample(LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGameLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    LitemallGameLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallGameLog record, @Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallGameLog record, @Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGameLog record, @Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGameLog record, @Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGameLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallGameLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}