package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRechargeRule;
import org.linlinjava.litemall.db.domain.LitemallRechargeRuleExample;

public interface LitemallRechargeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int insert(LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRechargeRule selectOneByExample(LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRechargeRule selectOneByExampleSelective(@Param("example") LitemallRechargeRuleExample example, @Param("selective") LitemallRechargeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRechargeRule> selectByExampleSelective(@Param("example") LitemallRechargeRuleExample example, @Param("selective") LitemallRechargeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    List<LitemallRechargeRule> selectByExample(LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRechargeRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRechargeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    LitemallRechargeRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRechargeRule selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallRechargeRule record, @Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallRechargeRule record, @Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRechargeRule record, @Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRechargeRule record, @Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRechargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallRechargeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}