package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGameUser;
import org.linlinjava.litemall.db.domain.LitemallGameUserExample;

public interface LitemallGameUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int insert(LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameUser selectOneByExample(LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameUser selectOneByExampleSelective(@Param("example") LitemallGameUserExample example, @Param("selective") LitemallGameUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallGameUser> selectByExampleSelective(@Param("example") LitemallGameUserExample example, @Param("selective") LitemallGameUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    List<LitemallGameUser> selectByExample(LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGameUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    LitemallGameUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallGameUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallGameUser record, @Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallGameUser record, @Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGameUser record, @Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGameUser record, @Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGameUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallGameUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_game_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}