package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPointLog;
import org.linlinjava.litemall.db.domain.LitemallPointLogExample;

public interface LitemallPointLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int insert(LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPointLog selectOneByExample(LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPointLog selectOneByExampleSelective(@Param("example") LitemallPointLogExample example, @Param("selective") LitemallPointLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPointLog> selectByExampleSelective(@Param("example") LitemallPointLogExample example, @Param("selective") LitemallPointLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    List<LitemallPointLog> selectByExample(LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPointLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPointLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    LitemallPointLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPointLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallPointLog record, @Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallPointLog record, @Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPointLog record, @Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPointLog record, @Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}