package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallExchangeLog;
import org.linlinjava.litemall.db.domain.LitemallExchangeLogExample;

public interface LitemallExchangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int insert(LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExchangeLog selectOneByExample(LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExchangeLog selectOneByExampleSelective(@Param("example") LitemallExchangeLogExample example, @Param("selective") LitemallExchangeLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallExchangeLog> selectByExampleSelective(@Param("example") LitemallExchangeLogExample example, @Param("selective") LitemallExchangeLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    List<LitemallExchangeLog> selectByExample(LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExchangeLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallExchangeLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    LitemallExchangeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExchangeLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallExchangeLog record, @Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallExchangeLog record, @Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallExchangeLog record, @Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallExchangeLog record, @Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallExchangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_exchange_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}