package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMemberOrder;
import org.linlinjava.litemall.db.domain.LitemallMemberOrderExample;

public interface LitemallMemberOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int insert(LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberOrder selectOneByExample(LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberOrder selectOneByExampleSelective(@Param("example") LitemallMemberOrderExample example, @Param("selective") LitemallMemberOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallMemberOrder> selectByExampleSelective(@Param("example") LitemallMemberOrderExample example, @Param("selective") LitemallMemberOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    List<LitemallMemberOrder> selectByExample(LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMemberOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    LitemallMemberOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMemberOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallMemberOrder record, @Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallMemberOrder record, @Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMemberOrder record, @Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMemberOrder record, @Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallMemberOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}